[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
line_length = 100
known_future_library = "future"
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"
known_localfolder = """apps,config"""
