# Generated by Django 5.0.6 on 2024-05-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=64, null=True, unique=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("public", models.BooleanField(default=False)),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
