# Generated by Django 5.0.6 on 2024-05-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_dislikes"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="ranking",
            field=models.IntegerField(default=0),
        ),
    ]
